### PR TITLE
Implement Partial Search stubs

### PR DESCRIPTION
**Pull request by steved**
This PR adds support for [partial search](http://www.opscode.com/blog/2012/10/31/introducing-partial-search-for-opscode-hosted-chef/) as well as updating the tests and adding fixes for chef 11.6.

### CODE REVIEW

**Comment by bhouse** [comment]
:+1:

**Comment by coffeemancy** [comment]
Would love to see this merged...

**Comment by steved** [comment]
bump @fnichol

**Comment by bhouse** [comment]
bump

**Comment by mhenrixon** [comment]
:+1:

**Pull request closed without merging**
